### ISSUE TITLE
Thankyou!

### ISSUE THREAD

**Issue by DJTraffik** [briankendall/devreorder#10]
Sorry I dont have an issue, I just wanted to thank you for creating this little gem!
I have an IPAC and 2 Aimtrak lightguns in my arcade cabinet and I was close to pulling my hair out thanks to Windows and its constant re-ordering of my controllers.
I have added this program of yours to MAME and Retroarch and I can now sit back and enjoy my games.

Thankyou.

**Comment by briankendall** [comment]
You're welcome! :-)
