### ISSUE TITLE
Avira antivirus detects dinput8.dll as Adware/Elex.zfxjx

### ISSUE THREAD

**Issue by supersmo** [briankendall/devreorder#12]
Installing the 1.0.2 version and Avira quarantines it because it detects it as: Adware/Elex.zfxjx

Not sure about what you can do, but thought you should know about it.

**Comment by briankendall** [comment]
Perhaps the way devreorder poses as dinput8.dll and passes through to it is triggering a false positive? I suspect there's not much I can do on my end.

Can you tell Avira to whitelist that file?

**Comment by supersmo** [comment]
I have now submited both dinput8.dll files to Avira as false positives. I hope they whitelist them.

**Comment by supersmo** [comment]
It's now whitelisted :-)
Tested to extract the dlls to the desktop and they were no longer quarantined.
Closing this issue.
