### ISSUE TITLE
Stopped working after newest W10 update

### ISSUE THREAD

**Issue by Qrusher14242** [briankendall/devreorder#13]
I'm on 1809 and the  Build # is 17763.55. I believe it just updated a day or two ago and every since then, i can't get it to work. It had been working fine for a while. I have a 360 controller that has a bad cable and it disconnects and then reconnects as like player 2 or 3. Some games are ok and keep working ( like mafia  3) but Dragon Quest XI and others don't work unless its P1. So i got it setup and worked fine. 

But every since the last windows update, i can't get it to work. I did the dll switch and checked over and over that it was the right ones. But i can't get the controller to work in those games if its on anything other than P2.  Any ideas?

**Comment by briankendall** [comment]
How did you install devreorder? Did you follow the "Apply to single game or program" instructions or the instructions for installing it for your entire system?

**Comment by supersmo** [comment]
I'm on Windows 10 64 bit home edition version 1809 build # 17763.379 and can confirm that it's working for me. Tested both system wide and per game.

@Qrusher14242 If you're trying to apply a system wide installation, did you rename the original dinput8 dlls to exactly dinput8org.dll?

**Comment by briankendall** [comment]
Closing as it's been almost a year since this was opened and this doesn't seem to be a general Win 10 v1809 issue. @Qrusher14242 if you still need assistance please reply and I'll reopen this.
