### ISSUE TITLE
Bit Defender detecting file as a virus

### ISSUE THREAD

**Issue by Nightstorm1** [briankendall/devreorder#14]
A few weeks ago an update to Bit Defender started flagging the dll files specifically the x64 one as a virus and it happily quarantined it while it was in use.  Windows 10 didn't react too well to that as you might imagine.  Work around of course was to set exclusions in the AV.  Just wanted to let you know it was happening.

**Comment by briankendall** [comment]
Thanks for the info! That's too bad, but not at all unexpected given the dll tomfoolery devorder makes use of. I don't think there's much I can do other than warn people that this might happen in the readme or something like that.
