### ISSUE TITLE
Device Lister wont run

### ISSUE THREAD

**Issue by natep87** [briankendall/devreorder#15]
Hi

Thank you for your great solution to my arcade cabinet. I have been using the program for a while on a system wide install and got two new controllers the other day. I went back to device lister and now it is giving me a .net Framework error saying the program is not a valid Win32 Applications HRESULT: 0x800700C1. 

I have tried going into windows features and unchecking both .net and then rechecking after restart and still the same issues. 

Wondering if anyone else has had this experience. Or has any easy solution to get the device ids. 

Regards

**Comment by natep87** [comment]
Also to the reason I don't use the control panel is that i have Joystick names the same and I am using the GUID to properly configure them.

**Comment by briankendall** [comment]
@natep87 What version of Windows are you running, and is it 32-bit or 64-bit?

**Comment by natep87** [comment]
Windows 10 and 64bit. Not sure what changed other than automatic updates between it working and not. Thanks for the quick reply.

**Comment by natep87** [comment]
I had another issue that didn't seem to have a fix and ended up formating the PC. All is working again so it must have been something corrupt in the OS.

**Comment by briankendall** [comment]
Great, glad to hear you got it sorted out
