### ISSUE TITLE
Enhance => Whitelist or Show section

### ISSUE THREAD

**Issue by DarkKinof** [briankendall/devreorder#16]
hi
first, thank for your amazing work, finally i can use my pads correctly sorted.
my wish will be the possibility to implement whitelist option.
why?
Because i have those "big problems":
-I use xinput pads on xinput games (FINE)
-I use xinput pads on dinput games trough virtual dinput pad (FINE)

Problem 1:
every time a dinput pad was plugged into the system (wiimote, DS4, generic pad) it was shown into the system.
every time a xinput pad was plugged into the system, it was shown as xinput and dinput device.
and it is a problem?
well, some (very old) games and programs have a ¿stupid? problem.
if they detect more that 4 pad plugged in the system (my 4 virtual dinput pad shorted with your program + the real dinput pads), they crash!!!

Problem 2:
while xinput pads have an "unique Id access model" (select pad 1 to 4 to access xinput pads without any problem), every manufacturer has is own Hardware ID (VID + PID).
i found more that 20 different Hardware IDs on xinput pads, and every new xinput pads model has another new Hardware ID.
it is impossible to me know all possible Hardware IDs and include into [HIDE] section.

if you can include [whitelist] section, both problems will be gone, i can put inside the Hardware IDs of virtual dinput pads, and no other pads will be show ever.
thanks for your time.
regards.

**Comment by briankendall** [comment]
A whitelist option is a great idea. I have a few games myself that I'd prefer not be able to see any DirectInput controllers except a specific few. I can't make any promises as to when I can get around to implementing it, and it probably won't be soon given how busy I typically am, but the next time I have some time to spend on devreorder I'll see if I can implement it.

**Comment by DarkKinof** [comment]
hi Briankendall
Thanks a lot for your time.
I know that "real life tasks" always must come first.
I will be hoping that you can make this improvement.
Regards.

**Comment by briankendall** [comment]
@DarkKinof It's been nine months but I just made a new release of devreorder that allows you to whitelist specific controllers. You can now add them to a `[visible]` section. Let me know if you try it out and find a bug.
