### ISSUE TITLE
Using Apply to your entire system crashes TrackIR

### ISSUE THREAD

**Issue by OverDhill** [briankendall/devreorder#19]
Had one game that seems to require this but after I made the changes (and the game did work) I noticed that my TrackIR no longer works.  The application instantly closes with no errors.  I restore the system to the restore point and it all works.  

Not sure if this can be fixes but would love to see it work for this one game.  All other games that require reordering controllers I have work with the DLL in the game folder.

**Comment by briankendall** [comment]
If I get a chance I'll take a look at TrackIR and see if I can figure out why it's crashing, but there may be nothing I can do. Some apps seem to break when presented with a DLL that redirects to another one such as the one included with devreorder.

Does it only crash if you replace dinput8.dll in the Windows directory? Or will it crash is devreorder's copy of dinput8.dll is copied into the same folder as TrackIR's executable?

**Comment by OverDhill** [comment]
Well after some searching I found this.

The work around for TrackIR 5 crashing is to copy the original dinput8.dll from SysWOW64 to the TrackIR directory. 

Then doing the rest of your instructions.  It worked for me.

**Comment by briankendall** [comment]
> I do have one question. If there is a game that that initializes DirectInput via the COM interface like I have (the reason I chose to implement this for the entire system) will it only use the C:\ProgramData\devreorder\devreorder.ini or will it still be able to use the one in the game folder on these types of games?

@OverDhill I'm not sure actually. I don't think I currently have any software that uses DirectInput via the COM interface for testing it out. If I could find one to download and test I could answer your question and update the instructions.

**Comment by OverDhill** [comment]
Well the game I have that only would work using the whole system was Sky Gamblers: Storm Raiders on Steam.  The game would only use the last two controllers so I had to use devreorder to make Vjoy the last on the list.  Windows 10 is so much fun when it comes to controllers and ordering them.  I also found a game that still will not work even with this method.
