### ISSUE TITLE
file not found exception directx

### ISSUE THREAD

**Issue by ash73** [briankendall/devreorder#21]
Win 10, 64bit, DirectX 12, I get the following error when trying to run devicelister.exe

System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.DirectX.DirectInput, Version=1.0.2902.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.DirectX.DirectInput, Version=1.0.2902.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

**Comment by briankendall** [comment]
@ash73 Please try installing the [DirectX 9 runtime](https://www.microsoft.com/en-us/download/details.aspx?id=8109) and let me know if the issue is fixed.

**Comment by ash73** [comment]
@briankendall that fixed it just fine, many thanks!
