### ISSUE TITLE
Issue with mame and logitech wheel .

### ISSUE THREAD

**Issue by defre1976** [briankendall/devreorder#23]
I hope i could get some answers here regarding devreorder .
I try to let work devreorder in mame .
My controllers in devicelister . 

My controllers :
"Mayflash Wiimote PC Adapter": {348414e0-8550-11e9-8001-444553540000}
"Controller (Xbox One For Windows)": {020d1c00-b17e-11e9-8001-444553540000}
"Logitech G25 Racing Wheel USB": {44ae04b0-856f-11e9-8001-444553540000}
"Controller (XBOX 360 For Windows)": {9bdfa030-cce2-11e9-802a-444553540000}
"Mayflash Wiimote PC Adapter": {34877040-8550-11e9-8007-444553540000}
"Controller (XBOX 360 For Windows)": {9c89e9f0-cce2-11e9-802b-444553540000}
"Controller (Xbox One For Windows)": {045bee00-b17e-11e9-8002-444553540000}
"Mayflash Wiimote PC Adapter": {34885aa0-8550-11e9-800b-444553540000}
"Mayflash Wiimote PC Adapter": {348881b0-8550-11e9-800d-444553540000}

Like you see its a mess . Thats why i was searching after a solution .
So i found devreorder .

I tried this with mame .

I put my order like following :

"Controller (Xbox One For Windows)": {020d1c00-b17e-11e9-8001-444553540000}
"Controller (Xbox One For Windows)": {045bee00-b17e-11e9-8002-444553540000}
"Logitech G25 Racing Wheel USB": {44ae04b0-856f-11e9-8001-444553540000}
"Controller (XBOX 360 For Windows)": {9bdfa030-cce2-11e9-802a-444553540000}
"Controller (XBOX 360 For Windows)": {9c89e9f0-cce2-11e9-802b-444553540000}
"Mayflash Wiimote PC Adapter": {348414e0-8550-11e9-8001-444553540000}
"Mayflash Wiimote PC Adapter": {34877040-8550-11e9-8007-444553540000}
"Mayflash Wiimote PC Adapter": {34885aa0-8550-11e9-800b-444553540000}
"Mayflash Wiimote PC Adapter": {348881b0-8550-11e9-800d-444553540000}

And it works , my 2 xbox one controllers are on position 1 and 2 .
But My logitech wheel don't work , devreorder just ignore it .
Xbox 360 on position 3 and 4 . No logitech on position 3 ??? When trying it out in mame .
From the moment i remove the Dinput , my logitech wheel works again , but in the wrong order offcourse .

What could be the problem ? 
I tried devreorder in retroarch , and there it works , but like this ==>
And this don't work in mame . 

; devreorder settings
; Any line starting with ; is a comment and will be ignored

[order]
Controller (Xbox One For Windows)
{020d1c00-b17e-11e9-8001-444553540000}
Controller (Xbox One For Windows)
{045bee00-b17e-11e9-8002-444553540000
Logitech G25 Racing Wheel USB
{44ae04b0-856f-11e9-8001-444553540000}
Controller (XBOX 360 For Windows)
{9bdfa030-cce2-11e9-802a-444553540000}
Controller (XBOX 360 For Windows)
{9c89e9f0-cce2-11e9-802b-444553540000}

[hidden]

[visible]
Mayflash Wiimote PC Adapter
{348414e0-8550-11e9-8001-444553540000}
Controller (Xbox One For Windows)
{020d1c00-b17e-11e9-8001-444553540000}
Logitech G25 Racing Wheel USB
{44ae04b0-856f-11e9-8001-444553540000}
Controller (XBOX 360 For Windows)
{9bdfa030-cce2-11e9-802a-444553540000}
Mayflash Wiimote PC Adapter
{34877040-8550-11e9-8007-444553540000}
Controller (XBOX 360 For Windows)
{9c89e9f0-cce2-11e9-802b-444553540000}
Controller (Xbox One For Windows)
{045bee00-b17e-11e9-8002-444553540000}
Mayflash Wiimote PC Adapter
{34885aa0-8550-11e9-800b-444553540000}
Mayflash Wiimote PC Adapter
{348881b0-8550-11e9-800d-444553540000}

[ignored processes]

**Comment by briankendall** [comment]
Hi @defre1976. The problem is likely that you've configured devreorder.ini incorrectly. You want to use either the controller's name or its UUID, but not both.

Try using this configuration:

```; devreorder settings
; Any line starting with ; is a comment and will be ignored

[order]
{020d1c00-b17e-11e9-8001-444553540000}
{045bee00-b17e-11e9-8002-444553540000
{44ae04b0-856f-11e9-8001-444553540000}
{9bdfa030-cce2-11e9-802a-444553540000}
{9c89e9f0-cce2-11e9-802b-444553540000}

[hidden]

[visible]
{348414e0-8550-11e9-8001-444553540000}
{020d1c00-b17e-11e9-8001-444553540000}
{44ae04b0-856f-11e9-8001-444553540000}
{9bdfa030-cce2-11e9-802a-444553540000}
{34877040-8550-11e9-8007-444553540000}
{9c89e9f0-cce2-11e9-802b-444553540000}
{045bee00-b17e-11e9-8002-444553540000}
{34885aa0-8550-11e9-800b-444553540000}
{348881b0-8550-11e9-800d-444553540000}

[ignored processes]
```
Also, since all controllers will be shown if the `[visible]` section is left empty, if you intend to have all of your controllers be visible then there's no need to add each of them to the `[visible]` section, unless you want to prevent any additional controllers you connect in the future from being visible.

**Comment by defre1976** [comment]
[order]
{020d1c00-b17e-11e9-8001-444553540000}
{045bee00-b17e-11e9-8002-444553540000}
{44ae04b0-856f-11e9-8001-444553540000}
{9bdfa030-cce2-11e9-802a-444553540000}
{9c89e9f0-cce2-11e9-802b-444553540000}

[hidden]

[visible]
{348414e0-8550-11e9-8001-444553540000}
{020d1c00-b17e-11e9-8001-444553540000}
{44ae04b0-856f-11e9-8001-444553540000}
{9bdfa030-cce2-11e9-802a-444553540000}
{34877040-8550-11e9-8007-444553540000}
{9c89e9f0-cce2-11e9-802b-444553540000}
{045bee00-b17e-11e9-8002-444553540000}
{34885aa0-8550-11e9-800b-444553540000}
{348881b0-8550-11e9-800d-444553540000}

[ignored processes]

No , still not working . I already tried this yesterday . 
Its ignoring everything now . 

for example Logitech wheel position 1
xbox one controllers position 8 and 9 
xbox 360 controllers trought out touchmote 6 and 7

It just ignore devreorder . 

but when  put this in my ini file . 
It works almost , only thing is my logitech wheel that i put on position 3 . 
mame ignore it , and set my 2 xbox controllers on position 1 and 2 . 
and xbox 360 controllers takes over 3 and 4 . 
Logitech wheel no work ? 
[order]
Controller (Xbox One For Windows)
{020d1c00-b17e-11e9-8001-444553540000}
Controller (Xbox One For Windows)
{045bee00-b17e-11e9-8002-444553540000
Logitech G25 Racing Wheel USB
{44ae04b0-856f-11e9-8001-444553540000}
Controller (XBOX 360 For Windows)
{9bdfa030-cce2-11e9-802a-444553540000}
Controller (XBOX 360 For Windows)
{9c89e9f0-cce2-11e9-802b-444553540000}

[hidden]

[visible]
Mayflash Wiimote PC Adapter
{348414e0-8550-11e9-8001-444553540000}
Controller (Xbox One For Windows)
{020d1c00-b17e-11e9-8001-444553540000}
Logitech G25 Racing Wheel USB
{44ae04b0-856f-11e9-8001-444553540000}
Controller (XBOX 360 For Windows)
{9bdfa030-cce2-11e9-802a-444553540000}
Mayflash Wiimote PC Adapter
{34877040-8550-11e9-8007-444553540000}
Controller (XBOX 360 For Windows)
{9c89e9f0-cce2-11e9-802b-444553540000}
Controller (Xbox One For Windows)
{045bee00-b17e-11e9-8002-444553540000}
Mayflash Wiimote PC Adapter
{34885aa0-8550-11e9-800b-444553540000}
Mayflash Wiimote PC Adapter
{348881b0-8550-11e9-800d-444553540000}

[ignored processes]

**Comment by defre1976** [comment]
sorry , my mistake , i mean when create my ini file like . 
then it almost works in mame . 
; devreorder settings
; Any line starting with ; is a comment and will be ignored

[order]
"Controller (Xbox One For Windows)": {020d1c00-b17e-11e9-8001-444553540000}
"Controller (Xbox One For Windows)": {045bee00-b17e-11e9-8002-444553540000}
"Logitech G25 Racing Wheel USB": {44ae04b0-856f-11e9-8001-444553540000}
"Controller (XBOX 360 For Windows)": {9bdfa030-cce2-11e9-802a-444553540000}
"Controller (XBOX 360 For Windows)": {9c89e9f0-cce2-11e9-802b-444553540000}
"Mayflash Wiimote PC Adapter": {348414e0-8550-11e9-8001-444553540000}
"Mayflash Wiimote PC Adapter": {34877040-8550-11e9-8007-444553540000}
"Mayflash Wiimote PC Adapter": {34885aa0-8550-11e9-800b-444553540000}
"Mayflash Wiimote PC Adapter": {348881b0-8550-11e9-800d-444553540000}

[hidden]

[visible]
"Mayflash Wiimote PC Adapter": {348414e0-8550-11e9-8001-444553540000}
"Controller (Xbox One For Windows)": {020d1c00-b17e-11e9-8001-444553540000}
"Controller (XBOX 360 For Windows)": {9bdfa030-cce2-11e9-802a-444553540000}
"Mayflash Wiimote PC Adapter": {34877040-8550-11e9-8007-444553540000}
"Controller (XBOX 360 For Windows)": {9c89e9f0-cce2-11e9-802b-444553540000}
"Controller (Xbox One For Windows)": {045bee00-b17e-11e9-8002-444553540000}
"Mayflash Wiimote PC Adapter": {34885aa0-8550-11e9-800b-444553540000}
"Logitech G25 Racing Wheel USB": {44ae04b0-856f-11e9-8001-444553540000}
"Mayflash Wiimote PC Adapter": {348881b0-8550-11e9-800d-444553540000}



[ignored processes]

I just tried to put the logitech wheel on position 5 , still no go :(
why oh why ???

**Comment by defre1976** [comment]
and when i do this , It put Logitech wheel in position 1 followed by xbox one controllers 2 and 3 . 
And xbox 360 controllers 4 and 5 ?

; devreorder settings
; Any line starting with ; is a comment and will be ignored

[order]
"Controller (Xbox One For Windows)": {020d1c00-b17e-11e9-8001-444553540000}
"Controller (Xbox One For Windows)": {045bee00-b17e-11e9-8002-444553540000}
"Controller (XBOX 360 For Windows)": {9bdfa030-cce2-11e9-802a-444553540000}
"Controller (XBOX 360 For Windows)": {9c89e9f0-cce2-11e9-802b-444553540000}
{44ae04b0-856f-11e9-8001-444553540000}
"Mayflash Wiimote PC Adapter": {348414e0-8550-11e9-8001-444553540000}
"Mayflash Wiimote PC Adapter": {34877040-8550-11e9-8007-444553540000}
"Mayflash Wiimote PC Adapter": {34885aa0-8550-11e9-800b-444553540000}
"Mayflash Wiimote PC Adapter": {348881b0-8550-11e9-800d-444553540000}

[hidden]

[visible]
"Mayflash Wiimote PC Adapter": {348414e0-8550-11e9-8001-444553540000}
"Controller (Xbox One For Windows)": {020d1c00-b17e-11e9-8001-444553540000}
"Controller (XBOX 360 For Windows)": {9bdfa030-cce2-11e9-802a-444553540000}
"Mayflash Wiimote PC Adapter": {34877040-8550-11e9-8007-444553540000}
"Controller (XBOX 360 For Windows)": {9c89e9f0-cce2-11e9-802b-444553540000}
"Controller (Xbox One For Windows)": {045bee00-b17e-11e9-8002-444553540000}
"Mayflash Wiimote PC Adapter": {34885aa0-8550-11e9-800b-444553540000}
{44ae04b0-856f-11e9-8001-444553540000}
"Mayflash Wiimote PC Adapter": {348881b0-8550-11e9-800d-444553540000}



[ignored processes]

**Comment by defre1976** [comment]
oh no , 

I just notice it also not work in retroarch . 
I start up retroarch , and then left below you see popping up all the controllers . 
I see xbox one controller position 0 and 1
Then i see logitech wheel not configured , no position 
after this i see xbox 360 controllers position 2 and 3 . 

Also here its ignoring my logitech wheel ? Could it be that devicelister is giving me the correct line to put in the devreorder.ini file ? ?

[order]
Controller (Xbox One For Windows)
{020d1c00-b17e-11e9-8001-444553540000}
Controller (Xbox One For Windows)
{045bee00-b17e-11e9-8002-444553540000
Logitech G25 Racing Wheel USB
{44ae04b0-856f-11e9-8001-444553540000}
Controller (XBOX 360 For Windows)
{9bdfa030-cce2-11e9-802a-444553540000}
Controller (XBOX 360 For Windows)
{9c89e9f0-cce2-11e9-802b-444553540000}

[hidden]

[visible]
Mayflash Wiimote PC Adapter
{348414e0-8550-11e9-8001-444553540000}
Controller (Xbox One For Windows)
{020d1c00-b17e-11e9-8001-444553540000}
Logitech G25 Racing Wheel USB
{44ae04b0-856f-11e9-8001-444553540000}
Controller (XBOX 360 For Windows)
{9bdfa030-cce2-11e9-802a-444553540000}
Mayflash Wiimote PC Adapter
{34877040-8550-11e9-8007-444553540000}
Controller (XBOX 360 For Windows)
{9c89e9f0-cce2-11e9-802b-444553540000}
Controller (Xbox One For Windows)
{045bee00-b17e-11e9-8002-444553540000}
Mayflash Wiimote PC Adapter
{34885aa0-8550-11e9-800b-444553540000}
Mayflash Wiimote PC Adapter
{348881b0-8550-11e9-800d-444553540000}

[ignored processes]

**Comment by defre1976** [comment]
ah no sorry , i mistake its working in retroarch . When i go to input .
I see 1 xbox one ,2 xbox one , 3 logitech wheel , 4 xbox 360 and 5 xbox 360  . 
So thats fine . 
Now finding a solution for mame .

**Comment by briankendall** [comment]
Did you install devreorder system-wide, or individually for both MAME and RetroArch?

**Comment by defre1976** [comment]
no , only in the mame folder and retroarch folder

**Comment by briankendall** [comment]
I haven't tried using devreorder specifically with MAME, but possible reasons for it not working include:

1. You may have put the wrong version of dinput8.dll into MAME's folder. Use the Task Manager to check whether MAME is a 32-bit or 64-bit application and then use the correct corresponding version of dinput8.dll
2. You need to put devreorder's copy of dinput8.dll into a different folder. Perhaps you didn't put it in the same folder as MAME's exe file, or perhaps it needs to go in a different folder inside its program folder because MAME uses a non-standard DLL search path.
3. MAME may use a special method of accessing DirectInput that requires installing devreorder system-wide. If the above two options fail try installing it system-wide.

**Comment by defre1976** [comment]
I did system wide install , under control panel - printer and devices . I see the correct order . 
I removed previous devreorder install from the retroarch folder . 
Started retroarch , and there i see the correct order of my controllers . 
I had i good feeling about mame , i start mame64 . I start a game , and it totally ignore the order from devreorder ?  I am about to give up . 
There is another one for mame Stable controller id . There also i can not get it to work . 

I will do a system restore , because i see alot it is not working anymore with my controllers in Hyperspin and so .

**Comment by defre1976** [comment]
Hi , 

I got it working with Stable controller id from mame by watching this youtube video . 
But it took also long to get this working . But the person from the video put a link to his config file . 
And this helped me alot . 
https://docs.mamedev.org/advanced/devicemap.html
https://www.youtube.com/watch?v=YmjfwLuZ_X0&t=83s

Devreorder was also working , just my logitech wheel was ignored . Why , i don't know , tried everything . 

Looking forward to future releases of devreorder ! Keep up the great work . thx for the help .

**Comment by briankendall** [comment]
Great, glad to hear you got it working!
