### ISSUE TITLE
XInput Reordering

### ISSUE THREAD

**Issue by hifihedgehog** [briankendall/devreorder#31]
Hello there! I am interested in this functionality applying to the Xinput API. This software does everything I need in DirectInput but I would need it for XInput. My goal is this: I would like to seamlessly use one or more XInput wireless controllers in place of my arcade controls on occasion. Is there a way to permanently assign and automatically disable or lower the priority of my already connected XInput controllers, which in this case are two Brook Zero Pi Fighting Boards (two permanently attached Xinput controllers), so the wireless ones always take precedence over them but *only* when they are connected? I would be willing to foot a monetary bounty as added incentive.

**Comment by hifihedgehog** [comment]
Not the ideal solution but it works: this Sabrent USB hub offers individual power buttons for each port. My cabinet has a rear door so hitting these buttons to toggle the ports off is an acceptable workaround.

https://www.amazon.com/dp/B00JX1ZS5O/

**Comment by briankendall** [comment]
At least for the time being reordering Xinput controllers is out of scope for devreorder. And given the capabilities of XInput, I'm not even 100% sure there could be a good way to get controllers to be reordered consistently. I'm glad you found an acceptable workaround in the meantime.
