### ISSUE TITLE
Using with Star Citizen

### ISSUE THREAD

**Issue by sutex** [briankendall/devreorder#40]
I have the ini setup in Live and in the PTU . Yet in game my Vjoy ID Load order is messed up. 
https://robertsspaceindustries.com/spectrum/community/SC/forum/3/thread/binding-woes-the-controller-id-order-saga
Any suggestions?

Update FIXED:  Changed the dev reorder ini from 1,2,3 to 1,3,2 So in SC the Stick is 1, Throttle 2 and the Rudder is 3 input, which is what I want.  Thanks - to Theguymilly for the suggestion / reminder

**Comment by briankendall** [comment]
Sounds like you got it on your own. Glad devreorder could help.
