### ISSUE TITLE
TrackIR stops working

### ISSUE THREAD

**Issue by tiefox** [briankendall/devreorder#5]
in a X64 system Track IR 5 stops working when dinput8.dll gets replaced in C:\Windows\SysWOW64

The following error is given

![image](https://cloud.githubusercontent.com/assets/4186/25056497/8bc2d400-2169-11e7-9300-9f15d6c6b32c.png)

**Comment by tiefox** [comment]
Replacing only the System32 dinput8.dll and leaving the SysWOW64 seems to work for TrackIR 5 + Star Citizen

**Comment by Nightstorm1** [comment]
I believe the application is x86 but it does have x64 drivers for Windows 10.  The work around for TrackIR 5 crashing though is to copy the original dinput8.dll from SysWOW64 to the TrackIR directory.  I hope this helps.  It worked for me.

**Comment by GameOverture** [comment]
This error message happens when you mix up 32bit and 64bit DLLs.

[on x64 system]
System32 holds 64bit DLLs
SysWOW64 holds 32bit DLLs

It's counter intuitive so it's easy to mess up.

**Comment by briankendall** [comment]
Okay, thanks @Nightstorm1 and @GameOverture for the info. Is there any need for me to keep this issue open any longer?

**Comment by OverDhill** [comment]
Thanks for the fix.  This should be included in the instructions for others to follow.  

"copy the original dinput8.dll from SysWOW64 to the TrackIR directory"

**Comment by briankendall** [comment]
@OverDhill Good idea. I've added it to README.
