### ISSUE TITLE
Devreorder v1.0.4 Windows Defender Threat pop-up

### ISSUE THREAD

**Issue by iNgeon** [briankendall/devreorder#53]
Downjloaded version 1.0.4, get a Trojan:Script/Wacatac.B!ml pop-up on Windows 10 Pro 19045.5247

![image](https://github.com/user-attachments/assets/80c3f0b1-1a2d-4e38-a2a1-cae41dc3b777)

**Comment by briankendall** [comment]
You'll have to tell it to whitelist the file. Because devreorder uses DLL injection, a lot of anti malware apps are going to see it as malware.

**Comment by iNgeon** [comment]
Not sure about that, I do not get this with https://github.com/briankendall/devreorder/releases/tag/v1.0.3

**Comment by briankendall** [comment]
@iNgeon It's a false positive:

![Screenshot 2024-12-30 at 8 58 22 AM](https://github.com/user-attachments/assets/bd57a25d-7ead-49bb-b6f2-a977c8d3e5c7)
![Screenshot 2024-12-30 at 8 58 29 AM](https://github.com/user-attachments/assets/4dc896eb-6272-49df-af46-a50778d22ad8)


Whether or not you get it for any particular release of devreorder is basically a roll of the dice.
