### ISSUE TITLE
devreorder stopped working after the "Windows Creators Update"

### ISSUE THREAD

**Issue by supersmo** [briankendall/devreorder#6]
dinput8.dll was upgraded to version 10.0.15063.0 in the "Windows Creators Update".
When I replace dinput8.dll with the devreorder 1.0.1 dlls, joy.cpl no longer starts up.

When I check my windows version with the "winver" command I have Windows version 1703 (OS-version 15063.332)

The creators update can be installed through windows update or here: https://support.microsoft.com/en-us/instantanswers/d4efb316-79f0-1aa1-9ef3-dcada78f3fa0/get-the-windows-10-creators-update

Devreorder is absolutely brilliant! Would be great if it would work with the latest Windows version.

**Comment by briankendall** [comment]
Okay, I'll see if I can fix it at my next available opportunity!

**Comment by supersmo** [comment]
Great! Glad to see that you are still active on this project :-)

**Comment by briankendall** [comment]
@supersmo I just tested in Windows 10 with the Windows Creators Update installed. (Confirmed OS version 15063.) No crashes on my end, and joy.cpl is working correctly. I was able to hide a connected controller from both joy.cpl and a DirectInput game.

Could you try double checking that:
1. You renamed the original dinput8.dll in both Windows\System32 and Windows\SysWOW64 to dinput8org.dll
2. You copied the x64 devreorder dll into System32 and the x86 devreorder dll into SysWOW64.

**Comment by supersmo** [comment]
Thanks. You're right it's working now. The Windows update replaced the working dinptu8.dll and when I applied devreorder's dlls again I must've mixed up the 32 and 64 bit dlls.
It somehow felt natural to put 32 bit dll in System32 and 64 bit in SysWOW64. :-P
Thanks for testing on your end and pointing out my mistake. :-)

**Comment by briankendall** [comment]
@supersmo Yes I agree those directories are inconveniently named! Glad to hear you worked it out.
