### ISSUE TITLE
Sort by parent device / usb port ?

### ISSUE THREAD

**Issue by sduponch** [briankendall/devreorder#7]
Hi,

I have an Arcade cabinet with two Zero Delay USB Encoder on a PC.
As the two devices have the same name, is there a way to sort them by the USB port where they are connected ?

Best regards,
DUPONCHEEL Sébastien

**Comment by briankendall** [comment]
@sduponch Any particular reason you closed this issue?

**Comment by sduponch** [comment]
@briankendall no, i just plan to change my HID interfaces for an arduino/teensy++ based one.
But if you think this is possible :)

**Comment by briankendall** [comment]
It may be possible. Next time I have a chance I'll look into it.

**Comment by billwarnockjr** [comment]
I am having a very similar issue.  I bought these two arcade usb encoders from amazon.  They are the same HID, same name, use the same built in driver, etc,. I primarily use theses controllers for various emulators, but every time I reboot, Windows changes the order of the Joystick ID.  I've been looking around forever and stumbled upon devreorder, and my specific issue here. Do you think devreorder can help me?

**Comment by briankendall** [comment]
Closing as this is a duplicate of #8

**Comment by briankendall** [comment]
FYI: if anyone is still watching this issue, check out [release 1.0.2](https://github.com/briankendall/devreorder/releases/tag/v1.0.2)

**Comment by sduponch** [comment]
Testing it ASAP, thank you :)
